pipeline {
    agent any

    stages{
        stage("Calculadora"){
            steps {
                
                echo 'Calculadora que solo muestra'
                script
                {
                   def v1 = 2;
                   def v2 = 5;
                   def text = "Suma: ";
                   println v1 + v2;
                   text += v1 + v2;
                   text += " Resta: ";
                   text += v1 - v2;
                   text += " Multiplicacion: ";
                   text += v1 * v2;
                   text += " Division: ";
                   text += v1 * v2;
                   println text;
                   writeFile(file: "salida.txt", text: text)
                }
            }
        }
        
    }
}
